# Generated by Django 4.0.5 on 2022-07-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJwt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
            ],
        ),
    ]
